package com.example.lolip.firebasesamplebystr;

import java.util.ArrayList;
import java.util.Date;
import java.util.UUID;

/**
 * Tags: a list of tags generated by algorithm
 * Lat/Long: converted from LatLng object, the location of the item
 * Contact Phone: a phone number for contact
 * Timestamp: the time and date of the report
 * Photos: a list of Urls of uploaded photos related to the report
 */
public class ReportPOJO {
//    private UUID id;
    private ArrayList<String> tags;
    private double latitude;
    private double longitude;
    private String phoneNum;
    private Date timestamp;
    private ArrayList<String> photos;

    @Override
    public String toString() {
        return "ReportPOJO{" +
                "tags=" + tags +
                ", latitude='" + latitude + '\'' +
                ", longitude='" + longitude + '\'' +
                ", phoneNum='" + phoneNum + '\'' +
                ", timestamp=" + timestamp +
                ", photos=" + photos +
                '}';
    }

    public ReportPOJO() {

    }

//    public UUID getId() {
//        return id;
//    }
//
//    public void setId() {
//        this.id = UUID.randomUUID();
//    }

    public ArrayList<String> getTags() {
        return tags;
    }

    public void setTags(ArrayList<String> tags) {
        this.tags = tags;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public String getPhoneNum() {
        return phoneNum;
    }

    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public ArrayList<String> getPhotos() {
        return photos;
    }

    public void setPhotos(ArrayList<String> photos) {
        this.photos = photos;
    }
}
